# Generated by Django 4.0.6 on 2022-07-24 11:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='blank.png', upload_to='images/')),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
