version: '3.7'

services:
  web:
    build: .
    user: 1000:1000
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=aj^=dh3(f-g*s!%-()is326ky-)h!c1(s)fz+bp#4*1ego&tc1
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000